name: cbm

services:
  backend:
    container_name: cbm-backend
    image: cbm-backend:latest
    build:
      context: .
      dockerfile: CBM_SOLICITUDES/Dockerfile
    environment:
      - PORT=${PORT}
      - HOST=${HOST}
      - HOST_URL=${HOST_URL}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_SERVER=${SQL_SERVER}
      - SQL_ENCRYPT=${SQL_ENCRYPT}
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - CBM_SOLICITUDES/.env

  frontend:
    container_name: cbm-frontend
    image: cbm-frontend:latest
    build:
      context: .
      dockerfile: CBM_FRONTEND/Dockerfile

networks:
  default:
    name: cbm-network
    driver: bridge